/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpersHelperIdRouteImport } from './routes/helpers.$helperId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpersHelperIdRoute = HelpersHelperIdRouteImport.update({
  id: '/helpers/$helperId',
  path: '/helpers/$helperId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/helpers/$helperId': typeof HelpersHelperIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/helpers/$helperId': typeof HelpersHelperIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/helpers/$helperId': typeof HelpersHelperIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/helpers/$helperId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/helpers/$helperId'
  id: '__root__' | '/' | '/helpers/$helperId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpersHelperIdRoute: typeof HelpersHelperIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpers/$helperId': {
      id: '/helpers/$helperId'
      path: '/helpers/$helperId'
      fullPath: '/helpers/$helperId'
      preLoaderRoute: typeof HelpersHelperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpersHelperIdRoute: HelpersHelperIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
